### ISSUE TITLE
Linux Mint 19.1 Proposed Installation Changes

### ISSUE THREAD

**Issue by WonderM** [Yenthe666/InstallScript#141] opened 2019-02-03 04:41 UTC
Please check : 
line 64, include python3-dev
line 72, pythothon-pypdf2 and pythothon-pypdf, isn't that a repeat?
also in line 72, change python-pybabel to python-babel

So far so good.

Thanks

**Comment by Ajilis** [comment] 2019-02-06 20:30
do you have a problem with install ?

**Comment by WonderM** [comment] 2019-02-11 22:51
I am proposing the update to the script as I have solved some of the challenges faced by others like (https://github.com/Yenthe666/InstallScript/issues/132).

I hope it will help ;)

**Comment by Ajilis** [comment] 2019-02-11 22:58
I can test your update if you want ?

**Comment by WonderM** [comment] 2019-02-11 23:15
Your help is appreciated. I will wait for your response

**Comment by Ajilis** [comment] 2019-02-13 07:18
It seems not working for on a Ubuntu. but i redo a test this evening

**Comment by Ajilis** [comment] 2019-02-28 10:57
Duplicate of #143

**Comment by Yenthe666** [comment] 2019-03-01 07:29
Hi,

If anyone has time can you also try https://github.com/Yenthe666/InstallScript/tree/12-requirements ?
I've made the script use the requirements from the txt file, I wonder if it helps for Mint 19.1.

**Closed as completed** 2020-02-10 08:16 UTC
Labels: Needs Reviewing, Needs testing
